name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    environment: dev
    runs-on: windows-latest
    steps:
      - name: test secrets
        env: 
          TENANT_ID: ${{ secrets.TENANT_ID }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "${{ secrets.TENANT_ID }}"
          echo "${{ secrets.APPLICATION_ID }}"
          echo "${{ secrets.CLIENT_SECRET }}"
          echo "${{ env.TENANT_ID }}"
          echo "${{ env.APPLICATION_ID }}"
          echo "${{ env.CLIENT_SECRET }}"          
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
